/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOADSCARTCOORDVAR
#define ROOADSCARTCOORDVAR

#include "RooAbsReal.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooAdsCartCoordVar : public RooAbsReal {
public:
  enum AdsConfig { rp, rm }; 
  RooAdsCartCoordVar() {} ; 
  RooAdsCartCoordVar(const char *name, const char *title,
	      AdsConfig _c,
	      RooAbsReal& _xp,
	      RooAbsReal& _xm,
	      RooAbsReal& _yp,
	      RooAbsReal& _ym,
	      RooAbsReal& _rD,
	      RooAbsReal& _dD);
  RooAdsCartCoordVar(const RooAdsCartCoordVar& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooAdsCartCoordVar(*this,newname); }
  virtual ~RooAdsCartCoordVar();

protected:

  RooRealProxy xp;
  RooRealProxy xm;
  RooRealProxy yp;
  RooRealProxy ym;
  RooRealProxy rD;
  RooRealProxy dD;
  AdsConfig c;
 
  Double_t evaluate() const;

private:
  ClassDef(RooAdsCartCoordVar, 1);
};
 
#endif
