/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RooGlwCartCoordVar.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

RooGlwCartCoordVar::RooGlwCartCoordVar(const char *name, const char *title,
		 GlwConfig _c,
		 RooAbsReal& _xp,
		 RooAbsReal& _xm,
		 RooAbsReal& _yp,
		 RooAbsReal& _ym) :
	 RooAbsReal(name,title), 
	 c(_c),
	 xp("xp","xp",this,_xp),
	 xm("xm","xm",this,_xm),
	 yp("yp","yp",this,_yp),
	 ym("ym","ym",this,_ym)
{ 
} 


RooGlwCartCoordVar::RooGlwCartCoordVar(const RooGlwCartCoordVar& other, const char* name) :  
	RooAbsReal(other,name), 
	c(other.c),
	xp("xp",this,other.xp),
	xm("xm",this,other.xm),
	yp("yp",this,other.yp),
	ym("ym",this,other.ym)
{ 
} 

RooGlwCartCoordVar::~RooGlwCartCoordVar() { }


Double_t RooGlwCartCoordVar::evaluate() const 
{ 
  double _xp = double(xp);
  double _xm = double(xm);
  double _yp = double(yp);
  double _ym = double(ym);
  double _rb2 = (_xp*_xp + _xm*_xm + _yp*_yp + _ym*_ym)/2.;
  double _rcpp = 1. + _rb2 + _xm + _xp;
  if ( c==rcpp )
  	return _rcpp;
  if ( c==acpp )
  	return (_xm-_xp)/_rcpp; 
  assert(0);
  return -99.;
} 

ClassImp(RooGlwCartCoordVar)
